version: '3.8'
services:
  api:
    container_name: python_api
    build:
      context: ../../src/backend
      dockerfile: ../../deploy/docker/Dockerfile
    ports:
      - 8000:8000
    entrypoint: ["poetry","run","uvicorn","api.main_api:app","--host","0.0.0.0", "--port", "8000"]


  